# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import student_pb2 as student__pb2


class StudentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddPoint = channel.unary_unary(
                '/StudentService/AddPoint',
                request_serializer=student__pb2.AddPointRequest.SerializeToString,
                response_deserializer=student__pb2.AddPointResponse.FromString,
                )
        self.GetPoint = channel.unary_unary(
                '/StudentService/GetPoint',
                request_serializer=student__pb2.GetPointRequest.SerializeToString,
                response_deserializer=student__pb2.GetPointResponse.FromString,
                )
        self.UpdatePoint = channel.unary_unary(
                '/StudentService/UpdatePoint',
                request_serializer=student__pb2.UpdatePointRequest.SerializeToString,
                response_deserializer=student__pb2.UpdatePointResponse.FromString,
                )
        self.DeletePoint = channel.unary_unary(
                '/StudentService/DeletePoint',
                request_serializer=student__pb2.DeletePointRequest.SerializeToString,
                response_deserializer=student__pb2.DeletePointResponse.FromString,
                )
        self.GetAllPoints = channel.unary_stream(
                '/StudentService/GetAllPoints',
                request_serializer=student__pb2.GetAllPointsRequest.SerializeToString,
                response_deserializer=student__pb2.GetAllPointsResponse.FromString,
                )


class StudentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StudentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPoint,
                    request_deserializer=student__pb2.AddPointRequest.FromString,
                    response_serializer=student__pb2.AddPointResponse.SerializeToString,
            ),
            'GetPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoint,
                    request_deserializer=student__pb2.GetPointRequest.FromString,
                    response_serializer=student__pb2.GetPointResponse.SerializeToString,
            ),
            'UpdatePoint': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePoint,
                    request_deserializer=student__pb2.UpdatePointRequest.FromString,
                    response_serializer=student__pb2.UpdatePointResponse.SerializeToString,
            ),
            'DeletePoint': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePoint,
                    request_deserializer=student__pb2.DeletePointRequest.FromString,
                    response_serializer=student__pb2.DeletePointResponse.SerializeToString,
            ),
            'GetAllPoints': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAllPoints,
                    request_deserializer=student__pb2.GetAllPointsRequest.FromString,
                    response_serializer=student__pb2.GetAllPointsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'StudentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StudentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StudentService/AddPoint',
            student__pb2.AddPointRequest.SerializeToString,
            student__pb2.AddPointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StudentService/GetPoint',
            student__pb2.GetPointRequest.SerializeToString,
            student__pb2.GetPointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StudentService/UpdatePoint',
            student__pb2.UpdatePointRequest.SerializeToString,
            student__pb2.UpdatePointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/StudentService/DeletePoint',
            student__pb2.DeletePointRequest.SerializeToString,
            student__pb2.DeletePointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/StudentService/GetAllPoints',
            student__pb2.GetAllPointsRequest.SerializeToString,
            student__pb2.GetAllPointsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
