# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: student.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstudent.proto\"5\n\x0f\x41\x64\x64PointRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x0e\n\x06points\x18\x02 \x01(\x05\"4\n\x10\x41\x64\x64PointResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\x0fGetPointRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\"\"\n\x10GetPointResponse\x12\x0e\n\x06points\x18\x01 \x01(\x05\"8\n\x12UpdatePointRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x0e\n\x06points\x18\x02 \x01(\x05\"7\n\x13UpdatePointResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x12\x44\x65letePointRequest\x12\x12\n\nstudent_id\x18\x01 \x01(\t\"7\n\x13\x44\x65letePointResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x15\n\x13GetAllPointsRequest\":\n\x14GetAllPointsResponse\x12\x12\n\nstudent_id\x18\x01 \x01(\t\x12\x0e\n\x06points\x18\x02 \x01(\x05\x32\xa5\x02\n\x0eStudentService\x12/\n\x08\x41\x64\x64Point\x12\x10.AddPointRequest\x1a\x11.AddPointResponse\x12/\n\x08GetPoint\x12\x10.GetPointRequest\x1a\x11.GetPointResponse\x12\x38\n\x0bUpdatePoint\x12\x13.UpdatePointRequest\x1a\x14.UpdatePointResponse\x12\x38\n\x0b\x44\x65letePoint\x12\x13.DeletePointRequest\x1a\x14.DeletePointResponse\x12=\n\x0cGetAllPoints\x12\x14.GetAllPointsRequest\x1a\x15.GetAllPointsResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'student_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADDPOINTREQUEST']._serialized_start=17
  _globals['_ADDPOINTREQUEST']._serialized_end=70
  _globals['_ADDPOINTRESPONSE']._serialized_start=72
  _globals['_ADDPOINTRESPONSE']._serialized_end=124
  _globals['_GETPOINTREQUEST']._serialized_start=126
  _globals['_GETPOINTREQUEST']._serialized_end=163
  _globals['_GETPOINTRESPONSE']._serialized_start=165
  _globals['_GETPOINTRESPONSE']._serialized_end=199
  _globals['_UPDATEPOINTREQUEST']._serialized_start=201
  _globals['_UPDATEPOINTREQUEST']._serialized_end=257
  _globals['_UPDATEPOINTRESPONSE']._serialized_start=259
  _globals['_UPDATEPOINTRESPONSE']._serialized_end=314
  _globals['_DELETEPOINTREQUEST']._serialized_start=316
  _globals['_DELETEPOINTREQUEST']._serialized_end=356
  _globals['_DELETEPOINTRESPONSE']._serialized_start=358
  _globals['_DELETEPOINTRESPONSE']._serialized_end=413
  _globals['_GETALLPOINTSREQUEST']._serialized_start=415
  _globals['_GETALLPOINTSREQUEST']._serialized_end=436
  _globals['_GETALLPOINTSRESPONSE']._serialized_start=438
  _globals['_GETALLPOINTSRESPONSE']._serialized_end=496
  _globals['_STUDENTSERVICE']._serialized_start=499
  _globals['_STUDENTSERVICE']._serialized_end=792
# @@protoc_insertion_point(module_scope)
